src/main/java/com/slavon/controller/AdminPageController.java
package com.slavon.controller;

import com.slavon.entity.Person;
import com.slavon.service.PersonService;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;


@ManagedBean(name = "adminPageController")
@RequestScoped
public class AdminPageController {

    @ManagedProperty("#{personService}")
    private PersonService personService;

    public Person getUser() {
        String userLogin = FacesContext.getCurrentInstance().getExternalContext().getRemoteUser();
            return personService.getPersonByLogin(userLogin);
    }

    public String navigateToOrderList() {
        return "/pages/orderListPage?faces-redirect=true";
    }

    public String navigateToRepairerList() {
        return "/pages/repairerListPage?faces-redirect=true";
    }

    public String navigateToUserList() {
        return "/pages/userListPage?faces-redirect=true";
    }

    public PersonService getPersonService() {
        return personService;
    }

    public void setPersonService(PersonService personService) {
        this.personService = personService;
    }
}

src/main/webapp/pages/addOrderPage.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <title>Add order</title>
</h:head>

<h:body>
<ui:composition template="../templates/layout.xhtml">

    <ui:define name="content">
        <ui:param name="ctrl" value="#{addOrderController}" />
        <ui:param name="listCtrl" value="#{orderListController}" />
        <ui:param name="updateCtrl" value="#{updateOrderController}" />

        <h2 align="center" class="page_title">Add new order</h2>

        <h:form id="addForm">
            <p:growl id="message"/>
        <h:panelGrid columns="7">


            <h:column>
             <h:panelGrid>
                <f:facet name="header">Car</f:facet>
                 <h:selectOneMenu id="car_select" value="#{ctrl.targetOrder.car.carId}" required="true" requiredMessage="Please select a car">
                     <f:selectItem itemLabel=""/>
                    <f:selectItems value="#{listCtrl.cars}" var="car" itemValue="#{car.carId}" itemLabel="#{car.carNumber}"/>
                </h:selectOneMenu>
             </h:panelGrid>
             </h:column>

            <h:column>
            <h:panelGrid>
                <f:facet name="header">Client</f:facet>
                <h:selectOneMenu value="#{ctrl.targetOrder.clientId}">
                    <f:selectItem itemLabel=""/>
                    <f:selectItems value="#{listCtrl.clients}" var="person" itemValue="#{person.personId}" itemLabel="#{person.firstName} #{person.personLastName}"/>
                </h:selectOneMenu>
            </h:panelGrid>
            </h:column>


            <h:column>
            <h:panelGrid>
                <f:facet name="header">Order Status</f:facet>
                <h:selectOneMenu value="#{ctrl.targetOrder.orderStatus.orderStatusId}" required="true" requiredMessage="Please select Order Status">
                    <f:selectItem itemLabel=""/>
                    <f:selectItems value="#{listCtrl.orderStatuses}" var="status" itemValue="#{status.orderStatusId}" itemLabel="#{status.orderStatus}"/>
                </h:selectOneMenu>
            </h:panelGrid>
            </h:column>


            <h:column>
            <h:panelGrid>
                <f:facet name="header">Repairer</f:facet>
                <h:selectOneMenu value="#{ctrl.targetOrder.repairerId}">
                    <f:selectItem itemLabel=""/>
                    <f:selectItems value="#{listCtrl.repairers}" var="person" itemValue="#{person.personId}" itemLabel="#{person.firstName} #{person.personLastName}"/>
                </h:selectOneMenu>
            </h:panelGrid>
            </h:column>

            <h:column>
            <h:panelGrid>
                <f:facet name="header">Order Price</f:facet>
                <h:inputText value="#{ctrl.targetOrder.orderPrice}" size="10" />
            </h:panelGrid>
            </h:column>


            <h:column>
            <h:panelGrid>
                <f:facet name="header">Comments</f:facet>
                <h:inputText label="" value="#{ctrl.targetOrder.lastComment.commentText}" required="true" requiredMessage="Please leave the comment" size="15"/>
            </h:panelGrid>
            </h:column>

            <h:column>
            <h:panelGrid>
            <p:commandButton value="save" action="#{ctrl.confirmAddOrder}" update="addForm:message"/>

            <p:commandButton value="cancel" action="#{updateCtrl.cancelUpdateAction}" immediate = "true" update="addForm:message"/>
            </h:panelGrid>
            </h:column>
        </h:panelGrid>

        </h:form>

    </ui:define>

</ui:composition>

</h:body>
</html>

src/main/webapp/pages/adminpage.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

<h:head>

</h:head>

<h:body>

    <ui:composition template="../templates/layout.xhtml">
        <ui:define name="content" >
            <ui:param name="ctrl" value="#{adminPageController}" />
            <h1 class="greetings">
            <h:outputLabel styleClass="greetings" value="Welcome : #{ctrl.user.firstName}" />
            </h1>
            <div class="topspace"></div>

            <h:form rendered="#{request.isUserInRole('ROLE_ADMINISTRATOR') || request.isUserInRole('ROLE_BOSS')}">
                <p:growl id="message" for="message"/>
            <p:commandButton id="orders" styleClass="button" ajax="false" value="Orders" action="#{ctrl.navigateToOrderList()}" />
            </h:form>

            <h:form rendered="#{request.isUserInRole('ROLE_ADMINISTRATOR') || request.isUserInRole('ROLE_REPAIRER')}">
                <p:commandButton id="repairers" styleClass="button" ajax="false" value="Repairers" action="#{ctrl.navigateToRepairerList()}" />
            </h:form>

            <h:form rendered="#{request.isUserInRole('ROLE_ADMINISTRATOR') || request.isUserInRole('ROLE_BOSS')}">
                <p:commandButton id="users" styleClass="button" ajax="false" value="Users" action="#{ctrl.navigateToUserList()}" />
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>

</html>

src/main/webapp/pages/errorPage.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">

<h:head>
    <title>Error occurred</title>
</h:head>

<h:body>
<ui:composition template="../templates/layout.xhtml">

    <ui:define name="content">
       <h3 class="error_message">Something went wrong, please try again later</h3>
    </ui:define>

</ui:composition>

</h:body>
</html>

src/main/webapp/pages/orderListPage.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">

<h:head>
    <title>Orders</title>
</h:head>

<h:body>

<ui:composition template="../templates/layout.xhtml">

    <ui:define name="content">
        <ui:param name="ctrl" value="#{orderListController}" />
        <ui:param name="addCtrl" value="#{updateOrderController}" />



        <h2 align="center" class="page_title">Orders:</h2>

        <div align="center" style="vertical-align: top">
            <h:form rendered="#{request.isUserInRole('ROLE_ADMINISTRATOR')}">
                <h:commandButton styleClass="home_button" value="add new order" ajax="false" action="#{ctrl.addOrder}"/>
            </h:form>
        </div>

        <h:form id="ordersForm">
            <h:messages id="messages"/>
        <h:dataTable id="orders" value="#{ctrl.orders}" var="order" style="width: 100%">

            <h:column>
                <f:facet name="header">ID</f:facet>
                <h:outputText value="#{order.orderId}" />
            </h:column>

            <h:column>
                <f:facet name="header">Car</f:facet>
                <h:outputText value="#{order.car.carNumber}"/>
            </h:column>

            <h:column>
                <f:facet name="header">Client Name</f:facet>
                <h:outputText value="#{ctrl.getClient(order.clientId).firstName} #{ctrl.getClient(order.clientId).personLastName}"/>
            </h:column>

            <h:column>
                <f:facet name="header">Order Status</f:facet>
                <h:outputText value="#{order.orderStatus.orderStatus}"/>
            </h:column>

            <h:column>
                <f:facet name="header">Repairer Name</f:facet>
                <h:outputText value="#{ctrl.getRepairer(order.repairerId).firstName} #{ctrl.getRepairer(order.repairerId).personLastName}"/>
            </h:column>

            <h:column>
                <f:facet name="header">Order Price</f:facet>
                <h:outputText value="#{order.orderPrice}"/>
            </h:column>

            <h:column>
                <f:facet name="header">Comments</f:facet>
                <h:dataTable id = "comments" value="#{order.commentList}" var="comment" styleClass="align:left;">
                    <h:column>
                        #{comment.person.firstName} #{comment.person.personLastName} : #{comment.commentDateTime} #{comment.commentText}
                    </h:column>
                </h:dataTable>
            </h:column>

            <h:column>
                <f:facet name="header"/>
                <p:commandButton value="update order" action="#{addCtrl.editAction(order)}"/>
            </h:column>

        </h:dataTable>
    </h:form>
    </ui:define>

</ui:composition>

</h:body>
</html>

src/main/webapp/pages/repairerListPage.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
<h:head>
    <title>Repairers</title>
</h:head>

<h:body>

    <ui:composition template="../templates/layout.xhtml">

        <ui:define name="content">
            <ui:param name="ctrl" value="#{repairerListController}" />

            <h2 align="center" class="page_title">Repairers:</h2>

            <h:form id="repairersForm">
                <p:growl id="message"/>
                <h:dataTable id="repairers" value="#{ctrl.repairers}" var="repairer" style="width: 100%">

                    <h:column>
                        <f:facet name="header">ID</f:facet>
                        <h:outputText value="#{repairer.personId}" />
                    </h:column>

                    <h:column>
                        <f:facet name="header">Specialization</f:facet>
                        <ui:repeat value="#{repairer.specializations.toArray()}" var="specialization">
                        <h:outputText value="#{specialization.specializationName}"/> <br/>
                        </ui:repeat>
                    </h:column>

                    <h:column>
                        <f:facet name="header">Name</f:facet>
                        <h:outputText value="#{repairer.firstName} #{repairer.personPatronymic} #{repairer.personLastName}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">Telephone number</f:facet>
                        <h:outputText value="#{repairer.personTelephoneNumber}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">Order Number</f:facet>
                        <ui:repeat value="#{repairer.orders.toArray()}" var="order">
                            <h:outputText value="#{order.orderId}"/> <br/>
                        </ui:repeat>
                    </h:column>
                </h:dataTable>
            </h:form>
        </ui:define>

    </ui:composition>

</h:body>
</html>

src/main/webapp/pages/updateOrderPage.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<h:head>
    <title>Update order</title>
</h:head>

<h:body>
    <ui:composition template="../templates/layout.xhtml">
        <ui:define name="content">
            <ui:param name="ctrl" value="#{updateOrderController}" />
            <ui:param name="listCtrl" value="#{orderListController}" />

            <h2 align="center" class="page_title">Update order</h2>

            <h:form id="addForm">
                <p:growl id="message"/>
                <h:panelGrid columns="8">

                    <h:column>
                        <h:panelGrid>
                         <f:facet name="header">ID</f:facet>
                           <h:outputText value="#{ctrl.targetOrder.orderId}" />
                        </h:panelGrid>
                    </h:column>

                    <h:column>
                        <h:panelGrid>
                            <f:facet name="header">Car</f:facet>
                            <h:selectOneMenu id="car_select" value="#{ctrl.targetOrder.car.carId}">
                                <f:selectItem itemLabel="#{ctrl.targetOrder.car.carNumber}" itemValue="#{ctrl.targetOrder.car.carId}"/>
                                <f:selectItems value="#{listCtrl.cars}" var="car" itemValue="#{car.carId}" itemLabel="#{car.carNumber}"/>
                            </h:selectOneMenu>
                        </h:panelGrid>
                    </h:column>

                    <h:column>
                        <h:panelGrid>
                            <f:facet name="header">Client</f:facet>
                            <h:selectOneMenu value="#{ctrl.targetOrder.clientId}">
                                <f:selectItem itemLabel="#{listCtrl.getClient(ctrl.targetOrder.clientId).firstName} #{listCtrl.getClient(ctrl.targetOrder.clientId).personLastName}" itemValue="#{ctrl.targetOrder.clientId}"/>
                                <f:selectItems value="#{listCtrl.clients}" var="person" itemValue="#{person.personId}" itemLabel="#{person.firstName} #{person.personLastName}"/>
                            </h:selectOneMenu>
                        </h:panelGrid>
                    </h:column>


                    <h:column>
                        <h:panelGrid>
                            <f:facet name="header">Order Status</f:facet>
                            <h:selectOneMenu value="#{ctrl.targetOrder.orderStatus.orderStatusId}">
                                <f:selectItem itemLabel="#{ctrl.targetOrder.orderStatus.orderStatus}" itemValue="#{ctrl.targetOrder.orderStatus.orderStatusId}"/>
                                <f:selectItems value="#{listCtrl.orderStatuses}" var="status" itemValue="#{status.orderStatusId}" itemLabel="#{status.orderStatus}"/>
                            </h:selectOneMenu>
                        </h:panelGrid>
                    </h:column>


                    <h:column>
                        <h:panelGrid>
                            <f:facet name="header">Repairer</f:facet>
                            <h:selectOneMenu value="#{ctrl.targetOrder.repairerId}">
                                <f:selectItem itemLabel="#{listCtrl.getRepairer(ctrl.targetOrder.repairerId).firstName} #{listCtrl.getRepairer(ctrl.targetOrder.repairerId).personLastName}" itemValue="#{ctrl.targetOrder.repairerId}"/>
                                <f:selectItems value="#{listCtrl.repairers}" var="person" itemValue="#{person.personId}" itemLabel="#{person.firstName} #{person.personLastName}"/>
                            </h:selectOneMenu>
                        </h:panelGrid>
                    </h:column>

                    <h:column>
                        <h:panelGrid>
                            <f:facet name="header">Order Price</f:facet>
                            <h:inputText value="#{ctrl.targetOrder.orderPrice}" size="10" />
                        </h:panelGrid>
                    </h:column>


                    <h:column>
                        <h:panelGrid>
                            <f:facet name="header">Comments</f:facet>
                            <h:inputText value="#{ctrl.targetOrder.lastComment.commentText}" required="true" requiredMessage="Please leave the comment" size="10"/>
                        </h:panelGrid>
                    </h:column>
                <h:column>
                <h:panelGrid>
                        <p:commandButton value="save" action="#{ctrl.confirmUpdateOrder}" update="addForm:message"/>

                        <p:commandButton value="cancel" action="#{ctrl.cancelUpdateAction}" immediate = "true" update="addForm:message"/>

                </h:panelGrid>
                </h:column>
                </h:panelGrid>

            </h:form>

        </ui:define>

    </ui:composition>

</h:body>
</html>

src/main/webapp/pages/userListPage.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
<h:head>
    <title>Users</title>
</h:head>

<h:body>

    <ui:composition template="../templates/layout.xhtml">

        <ui:define name="content">
            <ui:param name="ctrl" value="#{userListController}"/>
            <ui:param name="adminCtrl" value="#{adminPageController}"/>

            <h2 align="center" class="page_title">Users:</h2>

            <div align="center" style="vertical-align: top">
                <h:form id="addUser" rendered="#{request.isUserInRole('ROLE_ADMINISTRATOR')}">
                    <p:commandButton styleClass="home_button" value="add user" ajax="true"
                                     actionListener="#{ctrl.addPerson}"
                                     update="editUser"
                                     oncomplete="PF('$editUser').show()"/>
                </h:form>
            </div>

            <h:form id="usersForm">
                <p:growl id="message"/>
                <h:dataTable id="users" value="#{ctrl.users}" var="user" style="width: 100%">

                    <h:column>
                        <f:facet name="header">ID</f:facet>
                        <h:outputText value="#{user.personId}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">Name</f:facet>
                        <h:outputText value="#{user.firstName} #{user.personPatronymic} #{user.personLastName}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">Email</f:facet>
                        <h:outputText value="#{user.personEmail}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">Telephone number</f:facet>
                        <h:outputText value="#{user.personTelephoneNumber}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">Login</f:facet>
                        <h:outputText value="#{user.personLogin}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">Password</f:facet>
                        <h:outputText value="#{user.personPassword}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">Role</f:facet>
                        <h:outputText value="#{user.personRole.roleName}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header"></f:facet>
                        <p:commandButton id="editUserBtn"
                                         value="edit" ajax="true"
                                         actionListener="#{ctrl.updatePerson(user)}"
                                         update="editUser"
                                         oncomplete="PF('$editUser').show()"/>
                        <p:commandButton id="deleteUserBtn" disabled="#{adminCtrl.user.personId==user.personId}"
                                         value="delete" ajax="true"
                                         actionListener="#{ctrl.updatePerson(user)}"
                                         oncomplete="PF('$confirmDeleteUser').show()"
                        />
                    </h:column>
                </h:dataTable>
            </h:form>

            <p:dialog id="editUser" header="Edit user" modal="true" widgetVar="$editUser" width="500">


                <h:form id="addForm">
                    <p:panelGrid columns="2">
                        <p:outputLabel value="ID" rendered="#{ctrl.userToUpdate.personId != 0}"/>
                        <h:outputText value="#{ctrl.userToUpdate.personId}"
                                      rendered="#{ctrl.userToUpdate.personId != 0}"/>
                        <p:outputLabel value="Name"/>
                        <p:inputText value="#{ctrl.userToUpdate.firstName}"/>
                        <p:outputLabel value="Patronymic"/>
                        <p:inputText value="#{ctrl.userToUpdate.personPatronymic}"/>
                        <p:outputLabel value="Last Name"/>
                        <p:inputText value="#{ctrl.userToUpdate.personLastName}"/>
                        <p:outputLabel value="Email"/>
                        <p:inputText value="#{ctrl.userToUpdate.personEmail}"/>
                        <p:outputLabel value="Telephone Number"/>
                        <p:inputText value="#{ctrl.userToUpdate.personTelephoneNumber}"/>
                        <p:outputLabel value="Login"/>
                        <p:inputText value="#{ctrl.userToUpdate.personLogin}" required="true"
                                     requiredMessage="Please input login"/>
                        <p:outputLabel value="Password"/>
                        <p:inputText value="#{ctrl.userToUpdate.personPassword}"/>
                        <p:outputLabel value="Role"/>
                        <h:selectOneMenu value="#{ctrl.userToUpdate.personRole.roleId}">
                            <f:selectItems value="#{ctrl.roles}" var="role" itemValue="#{role.roleId}"
                                           itemLabel="#{role.roleName}"/>
                        </h:selectOneMenu>
                        <f:facet name="footer">
                            <h:panelGroup style="display:block; text-align:center">
                                <p:commandButton id="submit" value="save" ajax="true"
                                                 actionListener="#{ctrl.confirmUpdatePerson()}"
                                                 process="@form"
                                                 update="usersForm"
                                                 oncomplete="if (args &amp;&amp; !args.validationFailed) PF('$editUser').hide()"/>
                                <p:commandButton id="cancelSave" value="cancel" onclick="PF('$editUser').hide()"/>

                            </h:panelGroup>
                        </f:facet>


                    </p:panelGrid>

                </h:form>


            </p:dialog>
            <p:dialog id="confirmDeleteUser" widgetVar="$confirmDeleteUser"
                      header="Are you sure you want to delete?" width="400" modal="true">
                <h:form>
                    <h:panelGroup style="display:block; text-align:center">

                        <p:commandButton id="delete" value="delete" ajax="true"
                                         actionListener="#{ctrl.confirmDeletePerson(ctrl.userToUpdate)}"
                                         update="usersForm"
                                         oncomplete="PF('$confirmDeleteUser').hide()"/>
                        <p:commandButton id="cancelDelete" value="cancel" onclick="PF('$confirmDeleteUser').hide()"/>

                    </h:panelGroup>
                </h:form>
            </p:dialog>
        </ui:define>

    </ui:composition>

</h:body>
</html>